-- Up Migration
-- Declarative metrics only. No SQL, compiler, execution or publication workflow.

CREATE TABLE app.metrics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metric_key uuid NOT NULL DEFAULT gen_random_uuid(),
  semantic_model_revision_id uuid NOT NULL,
  name varchar(63) NOT NULL,
  label varchar(200) NOT NULL,
  description varchar(2000),
  expression jsonb NOT NULL,
  CONSTRAINT metrics_revision_fk
    FOREIGN KEY (semantic_model_revision_id)
    REFERENCES app.semantic_model_revisions(id)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT metrics_id_revision_unique
    UNIQUE (id, semantic_model_revision_id),
  CONSTRAINT metrics_key_unique
    UNIQUE (semantic_model_revision_id, metric_key),
  CONSTRAINT metrics_name_unique
    UNIQUE (semantic_model_revision_id, name),
  CONSTRAINT metrics_name_valid
    CHECK (name ~ '^[a-z][a-z0-9_]{0,62}$'),
  CONSTRAINT metrics_label_nonempty
    CHECK (btrim(label) <> ''),
  CONSTRAINT metrics_description_nonempty
    CHECK (description IS NULL OR btrim(description) <> ''),
  CONSTRAINT metrics_expression_object
    CHECK (jsonb_typeof(expression) = 'object'),
  CONSTRAINT metrics_expression_v1_root
    CHECK (expression ->> 'version' = '1' AND expression ->> 'kind' = 'aggregate'),
  -- Application canonical JSON is limited to 16 KiB. The extra 1 KiB covers
  -- whitespace added by PostgreSQL jsonb text serialization.
  CONSTRAINT metrics_expression_size
    CHECK (octet_length(expression::text) <= 17408)
);

CREATE TABLE app.metric_field_references (
  metric_id uuid NOT NULL,
  semantic_model_revision_id uuid NOT NULL,
  field_key uuid NOT NULL,
  CONSTRAINT metric_field_references_pkey
    PRIMARY KEY (metric_id, field_key),
  CONSTRAINT metric_field_references_metric_fk
    FOREIGN KEY (metric_id, semantic_model_revision_id)
    REFERENCES app.metrics(id, semantic_model_revision_id)
    ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT metric_field_references_field_fk
    FOREIGN KEY (semantic_model_revision_id, field_key)
    REFERENCES app.semantic_fields(semantic_model_revision_id, field_key)
    ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE INDEX metric_field_references_field_idx
  ON app.metric_field_references (semantic_model_revision_id, field_key);

CREATE TRIGGER metrics_updated_at
BEFORE UPDATE ON app.metrics
FOR EACH ROW EXECUTE FUNCTION app.set_updated_at();

COMMENT ON COLUMN app.metrics.metric_key IS
  'Stable logical metric identity; generated by the server and preserved by draft edits.';
COMMENT ON COLUMN app.metrics.expression IS
  'Validated engine-independent Metric Expression AST v1. Never SQL.';
COMMENT ON TABLE app.metric_field_references IS
  'Relational projection of distinct field_key references from metrics.expression.';

-- Down Migration
DROP TABLE app.metric_field_references RESTRICT;
DROP TABLE app.metrics RESTRICT;
